FROM jenkins/jenkins:lts

USER root

# Docker CLI kurulumu
RUN curl -fsSL https://get.docker.com -o get-docker.sh && \
    sh get-docker.sh && \
    rm get-docker.sh && \
    docker --version

# Jenkins kullanıcısını docker grubuna ekle
RUN usermod -aG docker jenkins

USER jenkins

